
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://suhkgksrdpcrozfryfmk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InN1aGtna3NyZHBjcm96ZnJ5Zm1rIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NzI4MzAsImV4cCI6MjA1OTQ0ODgzMH0.1jBMK4kwclSBsY7BDisCFhTwKSSrRT3t4T93VxgRvtI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(
  SUPABASE_URL, 
  SUPABASE_PUBLISHABLE_KEY,
  {
    auth: {
      autoRefreshToken: true,
      persistSession: true,
      storage: localStorage
    }
  }
);
